<?php

/**
 * Model configurations
 * */

return [
 	 /**
       * Default primary key type
       * Options [GUID, AUTO]
       * Override this for a given model with PrimaryKey attribute on a model property passing in the type in the constructor
       * GUID values will be auto generated before insert, while AUTO values are generated by the db engine on insert
     **/
 	 'pk_type' => 'GUID',

	 /**
      * When creating models, usually you want to keep track of 
      * 1. Who added a row
      * 2. Who modified a row
      * 3. Who deleted a row
      * 4. When was a row added
      * 5. When was a row modified
      * 6. When was a row deleted
      * 
      * The settings below will enable automatic inclusion of these fields without explicitly defining them 
      * in all the models.
      * 
      * MODEL_AUTO_CM_FIELDS
      * - This flag tells the model to generate Created By and Modified By fields. The field type will be GUID or AUTO(INT)
      *   depending on what the PRIMARY_KEY_TYPE flag is set to.
      * - The specific names of the fields will be set by adding the flags MODEL_CREATED_BY_FIELD and MODEL_MODIFIED_BY_FIELD
      * 
      * MODEL_AUTO_CMDT_FIELDS
      * - This flag tells the model to generate Created At and Modified At date/datetime/time/timestamp fields. The field type will be derived from
      *   the DB_AUTO_CMDT_TYPE flag
      * - The specific names of the fields will be set by adding the flags MODEL_CREATED_AT_FIELD and MODEL_MODIFIED_AT_FIELD
      * 
      * MODEL_SOFT_DELETE
      * - This flag tells the model to generate Is Deleted, Deleted By and Deleted At fields. The Deleted By type will
      *   depend on the PRIMARY_KEY_TYPE flag and Deleted At type will depend on the DB_AUTO_CMDT_TYPE flag.
      * - The specific names of the fields will be set by adding the flags MODEL_DELETED_AT_FIELD and MODEL_DELETED_BY_FIELD and MODEL_DELETED_FIELD
      * 
      * All the flags below have model specific equivalents that can be used to override behavior from model to model
      * if that need arises.
      * */
     'with_user_audit' => true,
     'created_by_field' => 'added_by',
     'modified_by_field' => 'modified_by',

     'with_timestamps' => true,
     'created_at_field' => 'date_added',
     'modified_at_field' => 'last_modified',

     'with_soft_delete' => true,
     'deleted_at_field' => 'deleted_at',
     'deleted_by_field' => 'deleted_by',
     'deleted_field' => 'deleted',

     /**
      * What happens when duplicate data is encountered during insert or update operations.
      * 
      * Options include: 
      * ABORT_WITH_ERROR - Abort the insert or update operation and throw an exception
      * 
      * INSERT_MINUS_DUPLICATE - Insert only the data that is not duplicating
      * 
      * UPDATE_ON_DUPLICATE - Update the record that is already existing with incoming values and return the updated version.
      * 
      * RETURN_EXISTING - Return existing record(s) as it is. (alongside newly added ones if multiple records are being inserted)
      * 
      * Defaults to ABORT_WITH_ERROR
      * 
      * */
     'action_on_duplicate' => 'ABORT_WITH_ERROR',
]
?>