<?php

/**
 * Model configurations
 * */

return [
 	 /**
       * Default primary key type
       * Options [UUID, AUTO]
       * 
       * UUID primary key values are auto generated before insert, 
       * while AUTO values are generated by the db engine on insert
     **/
 	 'pk_type' => 'UUID',

	 /**
      * When creating models, usually you want to keep track of 
      * 1. Who added a row
      * 2. Who modified a row
      * 3. Who deleted a row
      * 4. When was a row added
      * 5. When was a row modified
      * 6. When was a row deleted
      * 7. Whether a row is deleted or not
      * 
      * The settings below will enable automatic inclusion or exclusion of these fields without explicitly defining them 
      * in all the models.
      * 
      * -------------------------------------------------------------------------------------
      * 
      * with_user_audit => true/false
      * - This flag tells the model to add these three fields:
      * 1. author - the user that creates a row
      * 2. modifier - the user that last updated a row
      * 3. remover - the user that deleted a row (If soft deletes are set)
      * 
      * - The above fields are OneToOne relation fields pointing to the User model.
      * - The specific names of the table columns associated with these fields are set with
      * the configurations:
      * 
      * author_column = 'author_id' //default, set yours if different
      * modifier_column = 'modifier_id' //default, set yours if different
      * remover_column = 'remover_id' //default, set yours if different
      * 
      * -------------------------------------------------------------------------------------
      * 
      * with_timestamps = true/false
      *
      * - This flag tells the model to add these three fields
      * 1. created_at - the timestamp of when a row is added. This is a DateTime field
      * 2. modified_at - the timestamp of when a row was last updated. This is a DateTime field
      * 3. removed_at - the timestamp of when the row was deleted. This is a DateTime field (If soft deletes are set)
      * 
      * - the specific names of the table columns associated with these fields are similar to the field names,
      * but can be changed with the configurations below:
      * 
      * created_at_column = 'created_at' //default, set yours if different
      * modified_at_column = 'modified_at' //default, set yours if different
      * removed_at_column = 'removed_at' //default, set yours if different
      * 
      * -------------------------------------------------------------------------------------
      * 
      * with_soft_delete = true/false
      * 
      * - This flag tells the model to add these fields
      * 1. is_removed - whether a row is deleted or not.
      * 2. removed_at (As explained above)
      * 3. remover (As explianed above)
      * 
      * Change column name
      * 
      * is_removed_column = 'is_removed' //default, set yours if different
      * 
      * */
     'with_user_audit' => true,
     //'author_column' => 'added_by',
     //'modifier_column' => 'modified_by',
     //'remover_column' => 'deleted_by',

     'with_timestamps' => true,
     //'created_at_column' => 'date_added',
     //'modified_at_column' => 'last_modified',
     //'removed_at_column' => 'deleted_at',

     'with_soft_delete' => true,
     //'is_removed_column' => 'deleted',

     /**
      * What happens when duplicate data is encountered during insert or update operations.
      * 
      * Options include: 
      * ABORT_WITH_ERROR - Abort the insert or update operation and throw an exception
      * 
      * INSERT_MINUS_DUPLICATE - Insert only the data that is not duplicating
      * 
      * UPDATE_ON_DUPLICATE - Update the record that is already existing with incoming values and return the updated version.
      * 
      * RETURN_EXISTING - Return existing record(s) as it is. (alongside newly added ones if multiple records are being inserted)
      * 
      * Defaults to ABORT_WITH_ERROR
      * 
      * */
     'action_on_duplicate' => 'ABORT_WITH_ERROR',
]
?>